name: ci/cd

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -f app/Dockerfile \
            -t ghcr.io/emirdaku/dotnetapp:8.0 \
            app/

      - name: Push Docker image
        run: docker push ghcr.io/emirdaku/dotnetapp:8.0

  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to VM with Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
           
            REPO_DIR="/home/azureuser/infrastructure-automation-platform"
            REPO_URL="https://x-access-token:${{ secrets.GH_PAT }}@github.com/emirdaku/infrastructure-automation-platform.git"

            
            if [ -d "$REPO_DIR" ]; then
                echo "Repo exists, updating..."
                cd "$REPO_DIR" || exit
                git reset --hard
                git clean -fd
                git remote set-url origin "$REPO_URL"
                git pull origin main
            else
                echo "Repo does not exist, cloning..."
                mkdir -p "$(dirname "$REPO_DIR")"
                git clone "$REPO_URL" "$REPO_DIR"
                cd "$REPO_DIR" || exit
            fi

            cd app
            if [ -f "docker-compose.yaml" ]; then
                echo "Starting containers with docker-compose..."
                docker-compose down --remove-orphans || true
                docker-compose pull
                docker-compose up -d --force-recreate
            else
                echo "docker-compose.yaml not found, skipping container start"
            fi




